//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceApp_ASP_Forms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int bookingID { get; set; }
        public Nullable<int> roomID { get; set; }
        public string username { get; set; }
        public System.DateTime bookingfrom { get; set; }
        public System.DateTime bookingto { get; set; }
        public Nullable<System.DateTime> checkedin { get; set; }
        public Nullable<System.DateTime> checkedout { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
