//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookRoom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bookings
    {
        public int BookingsID { get; set; }
        public Nullable<int> roomID { get; set; }
        public string username { get; set; }
        [DataType(DataType.Date)]
        public DateTime bookingfrom { get; set; }
        [DataType(DataType.Date)]
        public DateTime bookingto { get; set; }
        [DataType(DataType.Time)]
        public Nullable<DateTime> checkedin { get; set; }
        [DataType(DataType.Time)]
        public Nullable<DateTime> checkedout { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
